Checking the Migrations, Laravel Spatie and Routes - api
jrcfxx/to-do-list pull request #3
Opened 2024-08-05 12:36 UTC by jrcfxx

2024-08-19 16:35 UTC, brunorconte requested changes
Please revisit every Class, add and correct the constructor and methods description following this guideline:

/**
* This function does this and that
* 
* @param string $someParam
* @param string $someOtherParam
*
* @return void
*/

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/AuthController.php
> +    public function __construct(
missing comments

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/AuthController.php
> +    public function register(Request $request)
missing comments

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/AuthController.php
> +    public function login(Request $request)
missing comments

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/AuthController.php
> +    public function logout(Request $request)
missing comments

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/PermissionController.php
> +class PermissionController extends Controller
why is there an empty controller?

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/RoleController.php
> +class RoleController extends Controller
why is there an empty controller?

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/TaskChangeController.php
> +    public function __construct(private TaskChange $taskChange)
missing function description (params, return type, etc.)

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/TaskController.php
> +    public function __construct(
missing function description

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/TaskController.php
> +     *
missing param in the comments

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/UsersController.php
> +    public function __construct(private User $user)
missing comments about constructor description

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/UsersController.php
> +     * @param  \App\Models\User  $user
why is there a comment saying there is a param $user?

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/UsersController.php
> +     * @return \Illuminate\Http\Response
recommend spacing @params and @return

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/UsersController.php
> +     * @return \Illuminate\Http\Response
also wrong params here

2024-08-19 16:35 UTC, brunorconte commented on app/Http/Controllers/UsersController.php
> +     * @param  \App\Models\User  $user
wrong params

2024-08-22 17:56 UTC, jrcfxx commented on app/Http/Controllers/AuthController.php
> +    public function login(Request $request)
Done.

2024-08-22 17:56 UTC, jrcfxx commented on app/Http/Controllers/AuthController.php
> +    public function logout(Request $request)
Done.

2024-08-22 17:56 UTC, jrcfxx commented on app/Http/Controllers/PermissionController.php
> +class PermissionController extends Controller
Done.

2024-08-22 17:58 UTC, jrcfxx commented on app/Http/Controllers/UsersController.php
> +     * @param  \App\Models\User  $user
Fixed.

2024-08-22 17:58 UTC, jrcfxx commented on app/Http/Controllers/UsersController.php
> +     * @param  \App\Models\User  $user
Fixed.

2024-08-22 17:58 UTC, jrcfxx commented on app/Http/Controllers/UsersController.php
> +     * @return \Illuminate\Http\Response
Fixed.

2024-08-28 18:56 UTC, brunorconte approved these changes

2024-08-28 18:57 UTC, merged